param(
    [Parameter(Mandatory = $true)]
    [string]$Expert,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Period,
    [Parameter(Mandatory = $true)]
    [string]$SetFile,
    [Parameter(Mandatory = $true)]
    [string]$From,
    [Parameter(Mandatory = $true)]
    [string]$To,
    [ValidateSet(0, 1, 2)]
    [int]$Model = 0,
    [int]$Spread = 10,
    [switch]$Visual
)

. (Join-Path $PSScriptRoot "lib.ps1")

$sourceFile = Join-Path (Get-SourceRoot) ("Experts/{0}.mq4" -f $Expert)
& (Join-Path $PSScriptRoot "build.ps1") -Source $sourceFile -Terminal test

$presetName = Copy-PresetToTerminal -Terminal test -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal test
$terminalExe = Get-ExecutablePath -Terminal test -ExecutableName "terminal.exe"

$timestamp = New-Timestamp
$reportBaseName = "{0}-{1}-{2}-{3}" -f $Expert, $Symbol, $Period, $timestamp
$reportRelativePath = "reports/$reportBaseName"
$reportOutputPath = Join-Path $terminalRoot ($reportRelativePath + ".htm")
$configPath = Get-ArtifactPath -RelativePath ("artifacts/backtest-{0}.ini" -f $timestamp)

$config = @"
; Generated by backtest.ps1
[Common]
Login=0
Password=
Server=
ProxyEnable=0

[Charts]
MaxBars=65000
MaxCharts=10

[Experts]
AllowLiveTrading=0
AllowDllImport=0
AllowImport=1

[Tester]
TestExpert=$Expert
TestExpertParameters=$presetName
TestSymbol=$Symbol
TestPeriod=$Period
TestModel=$Model
TestSpread=$Spread
TestOptimization=false
TestDateEnable=true
TestFromDate=$From
TestToDate=$To
TestReport=$reportRelativePath
TestReplaceReport=true
TestShutdownTerminal=true
TestVisualEnable=$($Visual.IsPresent.ToString().ToLowerInvariant())
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

$process = Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", $configPath) `
    -WorkingDirectory $terminalRoot `
    -PassThru `
    -Wait

if ($process.ExitCode -ne 0) {
    throw "Terminal exited with code $($process.ExitCode)."
}

if (-not (Test-Path -LiteralPath $reportOutputPath)) {
    throw "Backtest report was not created: $reportOutputPath"
}

& (Join-Path $PSScriptRoot "collect-logs.ps1") -Terminal test | Out-Null

$projectReportPath = Get-ArtifactPath -RelativePath ("reports/{0}.htm" -f $reportBaseName)
Copy-Item -LiteralPath $reportOutputPath -Destination $projectReportPath -Force
Write-Host "Report: $projectReportPath"

& (Join-Path $PSScriptRoot "parse-report.ps1") -Report $projectReportPath
