param(
    [Parameter(Mandatory = $true)]
    [string]$Expert,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Period,
    [Parameter(Mandatory = $true)]
    [string]$SetFile,
    [Parameter(Mandatory = $true)]
    [string]$From,
    [Parameter(Mandatory = $true)]
    [string]$To,
    [ValidateSet(0, 1, 2)]
    [int]$Model = 0,
    [int]$Spread = 10,
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = "",
    [switch]$Visual
)

. (Join-Path $PSScriptRoot "lib.ps1")

$platform = Get-TerminalPlatform -Terminal test
if ($platform -ne "mt5") {
    throw "Backtest script currently supports MQL5 only. Terminal 'test' is '$platform'. Install MT5 (MQL5)."
}

$sourceFile = Join-Path (Get-SourceRoot) ("Experts/{0}.mq5" -f $Expert)
& (Join-Path $PSScriptRoot "build.ps1") -Source $sourceFile -Terminal test

$presetName = Copy-PresetToTerminal -Terminal test -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal test
$terminalExe = Get-TerminalExecutable -Terminal test -Kind terminal

$timestamp = New-Timestamp
$reportBaseName = "{0}-{1}-{2}-{3}" -f $Expert, $Symbol, $Period, $timestamp
$reportRelativePath = "reports\$reportBaseName.xml"
$reportOutputPath = Join-Path $terminalRoot $reportRelativePath
$configPath = Get-ArtifactPath -RelativePath ("artifacts/backtest-{0}.ini" -f $timestamp)

$config = @"
; Generated by backtest.ps1
[Common]
Login=$Login
Password=$Password
Server=$Server
ProxyEnable=0

[Charts]
MaxBars=65000
MaxCharts=10

[Experts]
AllowLiveTrading=0
AllowDllImport=0
AllowImport=1

[Tester]
Expert=$Expert
ExpertParameters=$presetName
Symbol=$Symbol
Period=$Period
Model=$Model
ExecutionMode=0
Optimization=0
FromDate=$From
ToDate=$To
Report=$reportRelativePath
ReplaceReport=1
ShutdownTerminal=1
Visual=$([int]$Visual.IsPresent)
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

$process = Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", "/config:$configPath") `
    -WorkingDirectory $terminalRoot `
    -PassThru `
    -Wait

if ($process.ExitCode -ne 0) {
    throw "Terminal exited with code $($process.ExitCode)."
}

& (Join-Path $PSScriptRoot "collect-logs.ps1") -Terminal test | Out-Null

if (Test-Path -LiteralPath $reportOutputPath) {
    $projectReportPath = Get-ArtifactPath -RelativePath ("reports/{0}.xml" -f $reportBaseName)
    Copy-Item -LiteralPath $reportOutputPath -Destination $projectReportPath -Force
    Write-Host "Report: $projectReportPath"
    & (Join-Path $PSScriptRoot "parse-report.ps1") -Report $projectReportPath
} else {
    Write-Warning "Backtest finished but report was not generated. Using tester logs only."
}
