param(
    [Parameter(Mandatory = $true)]
    [string]$Expert,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Period,
    [Parameter(Mandatory = $true)]
    [string]$SetFile,
    [string]$Template = "demo.tpl",
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = ""
)

. (Join-Path $PSScriptRoot "lib.ps1")

$platform = Get-TerminalPlatform -Terminal demo
if ($platform -ne "mt5") {
    throw "Demo launch script currently supports MQL5 EA attachment only. Terminal 'demo' is '$platform'. Install MT5 (MQL5)."
}

$sourceFile = Join-Path (Get-SourceRoot) ("Experts/{0}.mq5" -f $Expert)
& (Join-Path $PSScriptRoot "build.ps1") -Source $sourceFile -Terminal demo

$presetName = Copy-PresetToTerminal -Terminal demo -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal demo
$terminalExe = Get-TerminalExecutable -Terminal demo -Kind terminal
$timestamp = New-Timestamp
$configPath = Get-ArtifactPath -RelativePath ("artifacts/demo-{0}.ini" -f $timestamp)

$config = @"
; Generated by demo-launch.ps1
[Common]
Login=$Login
Password=$Password
Server=$Server
ProxyEnable=0

[Experts]
AllowLiveTrading=1
AllowDllImport=0
AllowImport=1

[StartUp]
Symbol=$Symbol
Period=$Period
Template=$Template
Expert=$Expert
ExpertParameters=$presetName
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", "/config:$configPath") `
    -WorkingDirectory $terminalRoot | Out-Null

Write-Host "Demo terminal launched: $terminalRoot"
Write-Host "Config: $configPath"
