param(
    [Parameter(Mandatory = $true)]
    [string]$Expert,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Period,
    [Parameter(Mandatory = $true)]
    [string]$SetFile,
    [string]$Template = "demo.tpl",
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = ""
)

. (Join-Path $PSScriptRoot "lib.ps1")

$sourceFile = Join-Path (Get-SourceRoot) ("Experts/{0}.mq4" -f $Expert)
& (Join-Path $PSScriptRoot "build.ps1") -Source $sourceFile -Terminal demo

$presetName = Copy-PresetToTerminal -Terminal demo -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal demo
$terminalExe = Get-ExecutablePath -Terminal demo -ExecutableName "terminal.exe"
$timestamp = New-Timestamp
$configPath = Get-ArtifactPath -RelativePath ("artifacts/demo-{0}.ini" -f $timestamp)

$config = @"
; Generated by demo-launch.ps1
[Common]
Login=$Login
Password=$Password
Server=$Server
ProxyEnable=0

[Experts]
AllowLiveTrading=1
AllowDllImport=0
AllowImport=1

[StartUp]
Symbol=$Symbol
Period=$Period
Template=$Template
Expert=$Expert
ExpertParameters=$presetName
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", $configPath) `
    -WorkingDirectory $terminalRoot | Out-Null

Write-Host "Demo terminal launched: $terminalRoot"
Write-Host "Config: $configPath"
