param(
    [Parameter(Mandatory = $true)]
    [string]$Expert,
    [Parameter(Mandatory = $true)]
    [string]$Symbol,
    [Parameter(Mandatory = $true)]
    [string]$Period,
    [Parameter(Mandatory = $true)]
    [string]$SetFile,
    [string]$Template = "demo.tpl",
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = "",
    [string]$EnvFile = ".env",
    [string[]]$Indicators = @("SmartMoneyZones")
)

. (Join-Path $PSScriptRoot "lib.ps1")

function Read-DotEnv {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $values = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $values
    }

    $lines = Get-Content -LiteralPath $Path
    foreach ($line in $lines) {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*$') { continue }
        $parts = $line -split '=', 2
        if ($parts.Count -ne 2) { continue }
        $key = $parts[0].Trim()
        $value = $parts[1].Trim()
        if ($key -ne "") {
            $values[$key] = $value
        }
    }

    return $values
}

$projectRoot = Get-ProjectRoot
$envPath = if ([System.IO.Path]::IsPathRooted($EnvFile)) { $EnvFile } else { Join-Path $projectRoot $EnvFile }
$envValues = Read-DotEnv -Path $envPath

if ([string]::IsNullOrWhiteSpace($Login) -and $envValues.ContainsKey("MT5_LOGIN")) {
    $Login = $envValues["MT5_LOGIN"]
}

if ([string]::IsNullOrWhiteSpace($Password) -and $envValues.ContainsKey("MT5_PASSWORD")) {
    $Password = $envValues["MT5_PASSWORD"]
}

if ([string]::IsNullOrWhiteSpace($Server) -and $envValues.ContainsKey("MT5_SERVER")) {
    $Server = $envValues["MT5_SERVER"]
}

$platform = Get-TerminalPlatform -Terminal demo
if ($platform -ne "mt5") {
    throw "Demo launch script currently supports MQL5 EA attachment only. Terminal 'demo' is '$platform'. Install MT5 (MQL5)."
}

$sourceFile = Join-Path (Get-SourceRoot) ("Experts/{0}.mq5" -f $Expert)
& (Join-Path $PSScriptRoot "build.ps1") -Source $sourceFile -Terminal demo

foreach ($indicator in $Indicators) {
    if ([string]::IsNullOrWhiteSpace($indicator)) {
        continue
    }

    $indicatorSource = Join-Path (Get-SourceRoot) ("Indicators/{0}.mq5" -f $indicator)
    if (-not (Test-Path -LiteralPath $indicatorSource)) {
        Write-Warning "Indicator source not found, skip build: $indicatorSource"
        continue
    }

    & (Join-Path $PSScriptRoot "build.ps1") -Source $indicatorSource -Terminal demo
}

$presetName = Copy-PresetToTerminal -Terminal demo -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal demo
$terminalExe = Get-TerminalExecutable -Terminal demo -Kind terminal
$timestamp = New-Timestamp
$configPath = Get-ArtifactPath -RelativePath ("artifacts/demo-{0}.ini" -f $timestamp)

$config = @"
; Generated by demo-launch.ps1
[Common]
Login=$Login
Password=$Password
Server=$Server
ProxyEnable=0

[Experts]
AllowLiveTrading=1
AllowDllImport=0
AllowImport=1

[StartUp]
Symbol=$Symbol
Period=$Period
Template=$Template
Expert=$Expert
ExpertParameters=$presetName
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", "/config:$configPath") `
    -WorkingDirectory $terminalRoot | Out-Null

Write-Host "Demo terminal launched: $terminalRoot"
Write-Host "Config: $configPath"
