param(
    [string]$Symbol = "EURUSD",
    [string]$Period = "H1",
    [string]$SetFile = "SmartMoneyEA.set",
    [string]$From = "2024.01.01",
    [string]$To = "2024.12.31",
    [ValidateSet(0,1,2)]
    [int]$Model = 0,
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = "",
    [string]$EnvFile = ".env"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "lib-launchers.ps1")
. (Join-Path $PSScriptRoot "..\lib.ps1")

$credentials = Resolve-Mt5Credentials -Login $Login -Password $Password -Server $Server -EnvFile $EnvFile

$platform = Get-TerminalPlatform -Terminal test
if ($platform -ne "mt5") {
    throw "Test launcher supports MT5 only. Terminal 'test' is '$platform'."
}

$eaSource = Join-Path (Get-SourceRoot) "Experts/SmartMoneyEA.mq5"
$indicatorSource = Join-Path (Get-SourceRoot) "Indicators/SmartMoneyZones.mq5"

& (Join-Path $PSScriptRoot "..\build.ps1") -Source $eaSource -Terminal test
& (Join-Path $PSScriptRoot "..\build.ps1") -Source $indicatorSource -Terminal test

$presetName = Copy-PresetToTerminal -Terminal test -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal test
$terminalExe = Get-TerminalExecutable -Terminal test -Kind terminal
$timestamp = New-Timestamp
$configPath = Get-ArtifactPath -RelativePath ("artifacts/tester-visual-{0}.ini" -f $timestamp)

$reportBaseName = "SmartMoneyEA-{0}-{1}-{2}" -f $Symbol, $Period, $timestamp
$reportRelativePath = "reports\$reportBaseName.xml"

$config = @"
; Generated by tester-visual-smartmoneyea.ps1
[Common]
Login=$($credentials.Login)
Password=$($credentials.Password)
Server=$($credentials.Server)
ProxyEnable=0

[Experts]
AllowLiveTrading=0
AllowDllImport=0
AllowImport=1

[Tester]
Expert=SmartMoneyEA
ExpertParameters=$presetName
Symbol=$Symbol
Period=$Period
Model=$Model
ExecutionMode=0
Optimization=0
FromDate=$From
ToDate=$To
Report=$reportRelativePath
ReplaceReport=1
ShutdownTerminal=0
Visual=1
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", "/config:$configPath") `
    -WorkingDirectory $terminalRoot | Out-Null

Write-Host "Visual tester launched: $terminalRoot"
Write-Host "Expert: SmartMoneyEA | Symbol: $Symbol | Period: $Period | Dates: $From..$To"
Write-Host "Preset: $presetName"
Write-Host "Config: $configPath"
Write-Host "Tester starts automatically in Visual mode; you can pause/speed up/inspect trades in UI."
