param(
    [string]$Symbol = "EURUSD",
    [string]$Period = "H1",
    [string]$SetFile = "SmartMoneyEA.set",
    [string]$Login = "",
    [string]$Password = "",
    [string]$Server = "",
    [string]$EnvFile = ".env"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "lib-launchers.ps1")
. (Join-Path $PSScriptRoot "..\lib.ps1")

$projectRoot = Get-ProjectRoot
$credentials = $null
try {
    $credentials = Resolve-Mt5Credentials -Login $Login -Password $Password -Server $Server -EnvFile $EnvFile
} catch {
    Write-Warning "MT5 credentials were not loaded from .env/args. Terminal will be opened anyway; login may be required manually."
    $credentials = @{ Login = ""; Password = ""; Server = "" }
}

$platform = Get-TerminalPlatform -Terminal test
if ($platform -ne "mt5") {
    throw "Test launcher supports MT5 only. Terminal 'test' is '$platform'."
}

$eaSource = Join-Path (Get-SourceRoot) "Experts/SmartMoneyEA.mq5"
$indicatorSource = Join-Path (Get-SourceRoot) "Indicators/SmartMoneyZones.mq5"

& (Join-Path $PSScriptRoot "..\build.ps1") -Source $eaSource -Terminal test
& (Join-Path $PSScriptRoot "..\build.ps1") -Source $indicatorSource -Terminal test

$presetName = Copy-PresetToTerminal -Terminal test -SetFile $SetFile
$terminalRoot = Get-TerminalRoot -Terminal test
$terminalExe = Get-TerminalExecutable -Terminal test -Kind terminal
$timestamp = New-Timestamp
$configPath = Get-ArtifactPath -RelativePath ("artifacts/tester-ui-{0}.ini" -f $timestamp)

$config = @"
; Generated by tester-ui-smartmoneyea.ps1
[Common]
Login=$($credentials.Login)
Password=$($credentials.Password)
Server=$($credentials.Server)
ProxyEnable=0

[Experts]
AllowLiveTrading=0
AllowDllImport=0
AllowImport=1

[StartUp]
Symbol=$Symbol
Period=$Period
"@

Set-Content -LiteralPath $configPath -Value $config -Encoding ASCII

Start-Process -FilePath $terminalExe `
    -ArgumentList @("/portable", "/config:$configPath") `
    -WorkingDirectory $terminalRoot | Out-Null

Write-Host "Test terminal launched: $terminalRoot"
Write-Host "Preset copied: $presetName"
Write-Host "Open Strategy Tester (Ctrl+R), choose Expert=SmartMoneyEA, Symbol=$Symbol, Period=$Period, SetFile=$presetName, then press Start manually."
